name: sliding_up_panel2
description: A draggable Flutter widget that makes implementing a SlidingUpPanel much easier!
version: 4.0.0+1
homepage: https://github.com/Zotov-VD/sliding_up_panel

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
